---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

before_install:
 - sudo useradd -d /home/ansible-test-user ansible-test-user
 - sudo mkdir /home/ansible-test-user
 - sudo chown ansible-test-user:ansible-test-user /home/ansible-test-user

#services:
#  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook -i tests/inventory --syntax-check --list-tasks role.yml
  - ansible-playbook -i tests/inventory --connection=local --sudo -vvvv role.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
