---
- name: Install software on Fedora
  when: ansible_distribution == 'Fedora'
  become: true
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'tint2', state: 'present' }

- name: Install software on openSUSE
  when: ansible_os_family == 'Suse'
  become: true
  ansible.builtin.zypper:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'tint2', state: 'present' }
  - { name: 'tint2-lang', state: 'present' }

- name: Update software cache for pacman
  when: ansible_distribution == 'ArchLinux'
  become: true
  ansible.builtin.pacman:
    update_cache: yes
  changed_when: false

- name: Install software on ArchLinux
  when: ansible_distribution == 'ArchLinux'
  become: true
  ansible.builtin.pacman:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'tint2', state: 'present' }

- name: Update software cache for apt-get
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install software on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'tint2', state: 'present' }

- name: Install software on Debian
  when: ansible_distribution == 'Debian'
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'tint2', state: 'present' }

- name: Make sure config directory exist
  ansible.builtin.file:
    path: "~{{ config_owner }}/.config/tint2"
    state: directory
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700

- name: Configure tint2
  ansible.builtin.template:
    src: tint2rc.j2
    dest: "~{{ config_owner }}/.config/tint2/tint2rc"
    owner: "{{ config_owner }}"
    group: "{{ config_owner_primary_group }}"
    mode: 0700
