FROM ubuntu:16.10

RUN apt-get update \
  && apt-get install -y ansible \
  && useradd ansible-test-user \
  && mkdir /home/ansible-test-user \
  && chown ansible-test-user:ansible-test-user /home/ansible-test-user
