---
- name: Converge
  hosts: all
  vars:
    config_owner: ansible-test-user
    launcher_item_app:
      - '/usr/share/applications/chromium-browser.desktop'
      - '/usr/share/applications/pcmanfm.desktop'
      - '/usr/share/applications/atom.desktop'
      - '/usr/share/applications/keepassx2.desktop'
      - '/usr/share/applications/lxterminal.desktop'
  tasks:
    - name: "Include ansible-role-tint2"
      ansible.builtin.include_role:
        name: "ansible-role-tint2"
